"""Database package: connection + models + repositories."""

from core.database.connection import (
    AsyncSessionLocal,
    Base,
    close_db,
    db_init_failed,
    engine,
    get_db,
    get_db_context,
    init_db,
    is_db_configured,
)
from core.database.models import (
    LAUFFORM_VARIANT,
    Aggregate,
    Bbox,
    GlyphPair,
    Hand,
    Instance,
    PairInstance,
    QuizWord,
    Source,
    Style,
    Template,
    WordInstance,
)
from core.database.repositories import (
    AggregateRepository,
    BboxRepository,
    GlyphPairRepository,
    HandRepository,
    InstanceRepository,
    PairInstanceRepository,
    QuizWordRepository,
    SourceRepository,
    StyleRepository,
    TemplateRepository,
    WordInstanceRepository,
)


__all__ = [
    "Aggregate",
    "AggregateRepository",
    "AsyncSessionLocal",
    "Base",
    "Bbox",
    "BboxRepository",
    "GlyphPair",
    "GlyphPairRepository",
    "Hand",
    "HandRepository",
    "Instance",
    "InstanceRepository",
    "PairInstance",
    "PairInstanceRepository",
    "QuizWord",
    "QuizWordRepository",
    "Source",
    "SourceRepository",
    "Style",
    "StyleRepository",
    "LAUFFORM_VARIANT",
    "Template",
    "TemplateRepository",
    "WordInstance",
    "WordInstanceRepository",
    "close_db",
    "db_init_failed",
    "engine",
    "get_db",
    "get_db_context",
    "init_db",
    "is_db_configured",
]
